"""fix register:username

Revision ID: 7084f3d1956b
Revises: c5953bd70e33
Create Date: 2025-02-09 21:17:07.884556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7084f3d1956b"
down_revision: Union[str, None] = "c5953bd70e33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registers",
        sa.Column("username", sa.String(length=256), nullable=False),
    )
    op.create_unique_constraint(None, "registers", ["id"])
    op.drop_column("registers", "usernname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registers",
        sa.Column(
            "usernname",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "registers", type_="unique")
    op.drop_column("registers", "username")
    # ### end Alembic commands ###
