"""expire date

Revision ID: 9abd32efe663
Revises: ddf6785ed9d1
Create Date: 2025-01-12 10:42:59.429236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9abd32efe663"
down_revision: Union[str, None] = "ddf6785ed9d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "promos",
        "expire_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "promos",
        "expire_date",
        existing_type=sa.String(length=20),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
