"""default null true

Revision ID: c62d8985120f
Revises: 19025af8dc59
Create Date: 2025-01-10 14:18:23.064697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c62d8985120f"
down_revision: Union[str, None] = "19025af8dc59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_server_default=sa.text("'0'::bigint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_server_default=sa.text("'0'::bigint"),
    )
    # ### end Alembic commands ###
