"""last name to promocode

Revision ID: 4314f3edfe21
Revises: 42b7a0d57d0f
Create Date: 2025-01-04 11:19:13.497532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4314f3edfe21"
down_revision: Union[str, None] = "42b7a0d57d0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promos",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("promocode", sa.String(length=256), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("referal", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["users.chat_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("promocode"),
    )
    op.add_column(
        "users", sa.Column("promocode", sa.String(length=256), nullable=True)
    )
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "promocode")
    op.drop_table("promos")
    # ### end Alembic commands ###
