"""managers infobot

Revision ID: 46e2919816a5
Revises: d3a2c417f9b3
Create Date: 2025-02-03 07:35:37.836805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46e2919816a5"
down_revision: Union[str, None] = "d3a2c417f9b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots",
        sa.Column("managers", sa.ARRAY(sa.BigInteger()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("infobots", "managers")
    # ### end Alembic commands ###
