"""delete user id

Revision ID: ddf6785ed9d1
Revises: c9caae62130a
Create Date: 2025-01-10 14:36:01.930704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddf6785ed9d1"
down_revision: Union[str, None] = "c9caae62130a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
