"""registers table

Revision ID: c5953bd70e33
Revises: aee7e2f0b49d
Create Date: 2025-02-06 06:42:48.370932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5953bd70e33"
down_revision: Union[str, None] = "aee7e2f0b49d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("usernname", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("bot_username", sa.String(length=256), nullable=False),
        sa.Column("approve", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_username"],
            ["infobots.bot_username"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registers")
    # ### end Alembic commands ###
