"""last_name nullable

Revision ID: 24752ce9033f
Revises: 40abe59516be
Create Date: 2025-01-03 13:46:38.532713

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24752ce9033f"
down_revision: Union[str, None] = "40abe59516be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "infobots", ["id"])
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.drop_constraint(None, "infobots", type_="unique")
    # ### end Alembic commands ###
