"""bot_username

Revision ID: 05f9f8c3396a
Revises: 48079d05106e
Create Date: 2025-02-02 08:48:13.161785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05f9f8c3396a"
down_revision: Union[str, None] = "48079d05106e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots",
        sa.Column("bot_username", sa.String(length=256), nullable=False),
    )
    op.drop_column("infobots", "botlink")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots",
        sa.Column(
            "botlink",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("infobots", "bot_username")
    # ### end Alembic commands ###
