"""comp name and expire date

Revision ID: 195531434c6c
Revises: 4314f3edfe21
Create Date: 2025-01-05 07:16:00.656946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "195531434c6c"
down_revision: Union[str, None] = "4314f3edfe21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots",
        sa.Column("company_name", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "promos", sa.Column("expire_date", sa.DateTime(), nullable=True)
    )
    op.create_unique_constraint(None, "promos", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "promos", type_="unique")
    op.drop_column("promos", "expire_date")
    op.drop_column("infobots", "company_name")
    # ### end Alembic commands ###
