"""cascade

Revision ID: d5d2472081f2
Revises: 7084f3d1956b
Create Date: 2025-02-09 22:04:16.719732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5d2472081f2"
down_revision: Union[str, None] = "7084f3d1956b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "registers_bot_username_fkey", "registers", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "registers",
        "infobots",
        ["bot_username"],
        ["bot_username"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "registers", type_="foreignkey")
    op.create_foreign_key(
        "registers_bot_username_fkey",
        "registers",
        "infobots",
        ["bot_username"],
        ["bot_username"],
    )
    # ### end Alembic commands ###
