"""is admin to marketer with default 

Revision ID: bebc1305ca51
Revises: 195531434c6c
Create Date: 2025-01-05 08:37:59.876840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bebc1305ca51"
down_revision: Union[str, None] = "195531434c6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "marketer", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "marketer")
    # ### end Alembic commands ###
