"""fields with date

Revision ID: 22969fc4dc15
Revises: 7b6523a5ccf5
Create Date: 2025-02-02 07:49:49.720612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22969fc4dc15"
down_revision: Union[str, None] = "7b6523a5ccf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots", sa.Column("payedtill", sa.Date(), nullable=False)
    )
    op.create_unique_constraint(None, "infobots", ["id"])
    op.add_column("promos", sa.Column("expire_date", sa.Date(), nullable=True))
    op.create_unique_constraint(None, "promos", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "promos", type_="unique")
    op.drop_column("promos", "expire_date")
    op.drop_constraint(None, "infobots", type_="unique")
    op.drop_column("infobots", "payedtill")
    # ### end Alembic commands ###
