"""company nullable

Revision ID: d3a2c417f9b3
Revises: 05f9f8c3396a
Create Date: 2025-02-02 09:34:21.389440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3a2c417f9b3"
down_revision: Union[str, None] = "05f9f8c3396a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "infobots", "chat_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "infobots",
        "bot_username",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "infobots",
        "bot_username",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.alter_column(
        "infobots", "chat_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###
