"""default id false

Revision ID: 19025af8dc59
Revises: 7c204a388cf2
Create Date: 2025-01-10 14:13:48.726213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19025af8dc59"
down_revision: Union[str, None] = "7c204a388cf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_id_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_id_key", "users", ["id"])
    # ### end Alembic commands ###
