"""unique bot_username

Revision ID: aee7e2f0b49d
Revises: 46e2919816a5
Create Date: 2025-02-06 06:42:29.980654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aee7e2f0b49d"
down_revision: Union[str, None] = "46e2919816a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "infobots", ["bot_username"])
    op.drop_column("infobots", "managers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots",
        sa.Column(
            "managers",
            postgresql.ARRAY(sa.BIGINT()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "infobots", type_="unique")
    # ### end Alembic commands ###
