"""relashion promo user

Revision ID: 121aaa7a5e77
Revises: bebc1305ca51
Create Date: 2025-01-09 11:41:35.289324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "121aaa7a5e77"
down_revision: Union[str, None] = "bebc1305ca51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "balance", sa.BigInteger(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    # ### end Alembic commands ###
