"""delete infobot fields with date

Revision ID: 1b5c0b864bce
Revises: 22969fc4dc15
Create Date: 2025-02-02 07:51:23.221143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b5c0b864bce"
down_revision: Union[str, None] = "22969fc4dc15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("infobots", "payedtill")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots",
        sa.Column("payedtill", sa.DATE(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
