"""rel

Revision ID: aa0ce8f58739
Revises: 9abd32efe663
Create Date: 2025-01-18 10:42:03.269558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aa0ce8f58739"
down_revision: Union[str, None] = "9abd32efe663"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "infobots", "chat_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "infobots",
        "payedtill",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "infobots",
        "payedtill",
        existing_type=sa.String(length=256),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "infobots", "chat_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
