"""default id

Revision ID: 4de6116a36d1
Revises: c2a2a6941547
Create Date: 2025-01-10 14:08:06.119751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4de6116a36d1"
down_revision: Union[str, None] = "c2a2a6941547"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "infobots", ["id"])
    op.create_unique_constraint(None, "promos", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "promos", type_="unique")
    op.drop_constraint(None, "infobots", type_="unique")
    # ### end Alembic commands ###
