"""wb_token

Revision ID: 48079d05106e
Revises: 1b5c0b864bce
Create Date: 2025-02-02 08:26:49.367356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48079d05106e"
down_revision: Union[str, None] = "1b5c0b864bce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infobots", sa.Column("wb_token", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("infobots", "wb_token")
    # ### end Alembic commands ###
