"""init

Revision ID: 7b6523a5ccf5
Revises: 
Create Date: 2025-02-02 07:49:13.035847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b6523a5ccf5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("promocode", sa.String(length=256), nullable=True),
        sa.Column(
            "marketer", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "balance", sa.BigInteger(), server_default="0", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_table(
        "infobots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("botlink", sa.String(length=256), nullable=False),
        sa.Column("company_name", sa.String(length=256), nullable=True),
        sa.Column(
            "samples_ans", sa.ARRAY(sa.String(length=400)), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["users.chat_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "promos",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("promocode", sa.String(length=256), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("referal", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["users.chat_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("promocode"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promos")
    op.drop_table("infobots")
    op.drop_table("users")
    # ### end Alembic commands ###
